### PR TITLE
Validation fixes.

### PR DESCRIPTION
**Pull request by mmccall**
#### What does this PR do?

Spot fixes a number of FHIR validation errors. Know it is not passing tests, but putting in PR so I can itemize the changes:

- Organizations require either a name or identifier by rule. Cerner data contained organizations with no UNK on the encompassing org body, but UNKs within each field, creating effectively empty organizations. This now checks against that (for practitioner organizations only).
- MedicationStatement Status is required. Defaulting to ACTIVE when not known.
- Reaction Manifestation free-text was not being passed the annotations, and was therefore creating empty reaction manifestations.
- AllergyIntolerance verificationStatus is a required field. This now defaults to UNCONFIRMED if not known. clinicalStatus is required if verificationStatus is not entered-in-error, so it now defaults to ACTIVE. The value-set transformations also appeared too stringent. Completed allergy values are coming in for what appear to active allergies, but are being translated to a verification of REFUTED. This seems incorrect. I also relaxed the "aborted" logic, as "entered-in-error" appeared to stringent.
- The wrong field was being set on provenance component, needed to set what instead of id.
- Provenance object recorded is a required field, now set to the time the object is generated.
- Encounter status was not always defaulting correctly.
- Document Reference indexed field is required, it is now set to when the object is created.
- Immunization primary source is required, it is now defaulted to false if it is not known (cannot positively infer that it came from a primary source).
- transaction type wasn't actually getting set on the bundles; we were rebuilding them within the create transaction bundle.

#### Related JIRA tickets:

None.

#### Background/Context:

Ran 2 epic, 1 cerner, and 1 sample file through processing and surfaced these issues.  Will likely surface more when I do the 100 entry PHI run.

### CODE REVIEW

**Review by au2 — COMMENTED** [review]
Looks like we will violate this conditions now.

+ AllergyIntolerance.clinicalStatus SHALL be present if verificationStatus is not entered-in-error.
+ AllergyIntolerance.clinicalStatus SHALL NOT be present if verification Status is entered-in-error

**Review by au2 — CHANGES_REQUESTED** [review]
There are multiple spots in the ResourceTransformerImpl where null return value from tOrganization2Organization is not handled. They need to be updated.

**Comment by mmccall** [comment]
> Looks like we will violate this conditions now.
> 
> * AllergyIntolerance.clinicalStatus SHALL be present if verificationStatus is not entered-in-error.
> * AllergyIntolerance.clinicalStatus SHALL NOT be present if verification Status is entered-in-error

I'm pretty sure my changes made this rule obsolete, basically with the changes to the lookup table the status can never be 'entered-in-error' anymore, because it seemed wrong to me to infer that from the values on the CDA, instead what would have gone to 'entered-in-error' just goes to 'invalid'. As such, verificationStatus will not be entered-in-error, and clinical status SHALL be present (hence why we can just set it if it isn't there). If you disagree though, just LMK.

**Comment by mmccall** [comment]
> There are multiple spots in the ResourceTransformerImpl where null return value from tOrganization2Organization is not handled. They need to be updated.

This appears to be corrected once I resolved merge conflicts with the main branch. Steven changed this to return entryResults instead of organizations. I pushed the assignment of the entryResult organization to later in the function to allow his null checking to handle it.

**Review by au2 — CHANGES_REQUESTED** [review]
We are creating practitioner role without organization created. Take a look at line 899 in ResourceTransformerImpl.

**Comment by au2** [comment]
another spot is creating role without organization i think, line 778

**Review by au2 — APPROVED** [review]

**Pull request merged**
