### PR TITLE
Upmcdhir 351 medication dispense

### PR DESCRIPTION
**Pull request by au2**
#### What does this PR do?

This enables creation of Medication Dispense resource from Medication Dispense CDA object.

The code is already there, I just put it in Medication Statement resource creation since that handles Medication Activity cda object and Medication Dispense is in Medication Activity.

#### Related JIRA tickets:

UPMCFHIR-351

#### How should this be manually tested?

Take a look at the sample files and check what is generated for sample files. 

#### Background/Context:

NA

#### New JIRA tickets for clinical review required?

NA

### CODE REVIEW

**Review by mmccall — CHANGES_REQUESTED** [review]
My main questions are about the mapping itself.

- Medication Status going to code, looks like statusCode can only be aborted or completed (per the spec), but your status mapping is more complex than that and doesn't support aborted.

- we are mapping code to type, but I don't see this anywhere in the source spec.

- we are mapping the effective times to dosage > timing > event if they are SXCM_TS, which is fine I guess; I don't see it in the spec but assume it is there for a reason.

- we can get repeatNumber in, but I can't find anywhere to map it well.

- we may get in medication supply order, which Steven mapped to medication request, as a component of this. Would this be tough to map in?

**Comment by au2** [comment]
- statusCode can now has only two values
- removed code -> type
- i do not know why we are doing SXCM_TS either; but it works with the sample file so until we get other samples it is ok.
- i saw that too but could not find a spot in FHIR either.
- let's postpone this until seeing occurrence. it is not hard except maybe we might have to do deduplication since it is very possible that it will be the same Medication Request out of Medication Statement that Steven added.

**Review by mmccall — APPROVED** [review]
okie dokie, can you just put a ticket in the backlog we won't get to for request? Then lgtm.

**Comment by au2** [comment]
added a ticket.

**Pull request merged**
