### PR TITLE
Location fix

### PR DESCRIPTION
**Pull request by mmccall**
#### What does this PR do?

Backs out identifier from location object, also reviews the object for STU3 compliance.  My test doesn't really do anything, but there's no way to set the id on the object before posting it in.

I also ticketed out the location code translation, it's pretty involved if we want to support it.

#### Related JIRA tickets:

UPMCFHIR-138
UPMCFHIR-139
UPMCFHIR-140
UPMCFHIR-206

#### Background/Context:

Needed by encounters so had to make sure we supported it in FHIR.

### CODE REVIEW

**Review by au2 — CHANGES_REQUESTED** [review]
1) The test does not really verify this fix; if you add the code you removed back it will still pass. I would some ids to the cda participant role and test it that way.
2) Please remove unused "cgaTypeFactory" in LocationTest as eclipse warns.

**Comment by mmccall** [comment]
so I wanted to do what you were saying, but there is no .setId method on the participantRole object, because it's not supposed to have one. I don't know why there is a getIds, but without a setId I don't know how to actually do that. Do you have any insight?

**Comment by au2** [comment]
i think getIds().add(II) works

**Comment by mmccall** [comment]
you are smart and I am dumb.

**Comment by au2** [comment]
Hey, you're worthy, you're worthy!

**Review by au2 — APPROVED** [review]

**Pull request merged**
