### PR TITLE
Feature/upmcfhir 213 donot create multi practitioners

### PR DESCRIPTION
**Pull request by au2**
#### What does this PR do?

1) This prevents creation of multiple practitioners if they have the same CDA id.
2) This adds a FHIR id to PractitionerRole resources.

#### Related JIRA tickets:

UPMCFHIR-213

#### How should this be manually tested?

A test is available for each CCDA sample in CCDTransformerTest. Other CCDA files can be tested in there with adding a line.

#### Background/Context:

Each id in CCDA is supposed to be unique so we should not be creating extra resources for the same object.

#### New JIRA tickets for clinical review required?

NA

### CODE REVIEW

**Review by 5t33 — APPROVED** [review]
LGTM. Only issue I noticed is there isn't converage for representedOrganization -> practitionerRole.managingOrganization in tAssignedAuthor2Practitioner.

**Comment by jmfadeley** [comment]
Unit tests are showing two failures: 

`ValidatorTest` for `testRakiaBundle` throwing "FileNotFound" errors around `src\test\resources\Cerner\Person-RAKIA_TEST_DOC00001 (1).XML`. This folder wasn't checked in, and I'm guessing for reasons?

`IntegrationTest` again for `rakiaIntegration`, likely for similar reasons (again, references to that particular file).

**Comment by 5t33** [comment]
(in regards to my last comment) Specifically when running the resourceTransformationTests.

**Comment by 5t33** [comment]
> Unit tests are showing two failures:
> 
> `ValidatorTest` for `testRakiaBundle` throwing "FileNotFound" errors around `src\test\resources\Cerner\Person-RAKIA_TEST_DOC00001 (1).XML`. This folder wasn't checked in, and I'm guessing for reasons?
> 
> `IntegrationTest` again for `rakiaIntegration`, likely for similar reasons.

Yeah we aren't version controlling those.

**Comment by au2** [comment]
OK. I updated an issue in JIRA for coverage. Will not add more to this right now.

**Pull request merged**
