### PR TITLE
[UPMCFHIR-216] Changes for the OIDs, added Multum and NCI.

### PR DESCRIPTION
**Pull request by jmfadeley**
#### What does this PR do?
Adds the "multum" and "nci" OIDs to `tOid2Url`.

Pretty printing was caused by CTRL + Shift + F for Eclipse. Let me know if this causes problems. 

#### Related JIRA tickets:
UPMCFHIR-216.

#### How should this be manually tested?
Run `IntegrationTest`. Verify that "multum-drug-id" in the Rakia files now appears with a valid Oid in the `rakia_bundle.json`.

### CODE REVIEW

**Review by mmccall — CHANGES_REQUESTED** [review]
looks good, but could you write a simple test for it? It isn't tested in any existing test cases, and should probably take you all of 10 minutes.

**Comment by jmfadeley** [comment]
@mmccall So in a way, it's handled via the current `IntegrationTest` which is outputting the OID. Should I factor the test to deeply check the returned bundle for an OID match?

**Comment by mmccall** [comment]
that probably wouldn't work since it's only coming in on files we aren't versioning.  If you could do a unit test just specifically checking for those codes, would be helpful.  Just pass the function the OID and expect a string back.

**Comment by mmccall** [comment]
lgtm.

**Review by mmccall — APPROVED** [review]

**Pull request merged**
